### ISSUE TITLE
Where is the map? 

### ISSUE THREAD

**Issue by PeregrineTEL** [PeregrineTEL/TEKDB#31]

**Comment by rhodges** [comment]
Two places:
 * Open any 'place' record with associated GIS data in the tool ( [see here](http://tdntek.ecotrust.org/explore/places/20/?page=1&items_per_page=25&filter=&view=list&places=true) ), or
* Editing Place records ( [here is the same record in the admin](http://tdntek.ecotrust.org/admin/TEKDB/places/20/change/) )
